### ISSUE TITLE
Refatoração do Back-end

### ISSUE THREAD

**Issue by RRS92** [RRS92/SistemaGestaoEventosAcademicos#12]
As classes de DTO das entidades do projeto necessitam de refatoração para diminuir o número de classes a serem trabalhadas, fazendo assim com que cada entidade possua apenas uma classe de DTO equivalente.

**Comment by EvertonJuanX** [comment]
Refatorei o backend, criando apenas um DTO para cada entidade, ajustando suas chamadas nas demais camadas do sistema. Além disso, resolvi algumas issues no método de deletar, adicionando em algumas entidades, a exclusão por cascata.
